# -------------------------
# History
# -------------------------
export HISTSIZE=10000
export HISTFILESIZE=20000

shopt -s histappend


# -------------------------
# Colors
# -------------------------
export TERM=xterm-256color


# -------------------------
# Completion
# -------------------------
if [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi


# -------------------------
# Aliases
# -------------------------
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gs='git status'
alias gd='git diff'
alias gp='git pull'
alias gl='git log --oneline --graph --decorate'


# -------------------------
# Git branch prompt
# -------------------------
parse_git_branch()
{
    git branch 2>/dev/null |
    sed -e '/^[^*]/d' \
        -e 's/* \(.*\)/ (\1)/'
}


export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;33m\]\$(parse_git_branch)\[\033[00m\]\$ "